-- Seed DigitalOcean service catalog entries using the current control-plane schema.
-- sell_price_cents = base_cost_cents (no margin); adjust before going to production.
alter table if exists public.service_catalog
  drop constraint if exists service_catalog_provider_provider_sku_region_key;

insert into public.service_catalog (
  plan_code, service_type, provider, provider_sku, region,
  display_name, base_cost_cents, sell_price_cents, billing_cycle,
  vcpu, memory_mb, storage_gb, quota, metadata, is_active
) values
  -- VPS Basic 2 vCPU / 4 GB — 5 regions
  ('do-vps-basic-2vcpu-4gb-nyc3', 'vps'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'nyc3',
   'VPS Basic (2 vCPU / 4 GB)', 1200, 1200, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"bandwidth":"4TB"}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb","imageSlug":"ubuntu-22-04-x64"}'::jsonb, true),
  ('do-vps-basic-2vcpu-4gb-sfo3', 'vps'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sfo3',
   'VPS Basic (2 vCPU / 4 GB)', 1200, 1200, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"bandwidth":"4TB"}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb","imageSlug":"ubuntu-22-04-x64"}'::jsonb, true),
  ('do-vps-basic-2vcpu-4gb-fra1', 'vps'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'fra1',
   'VPS Basic (2 vCPU / 4 GB)', 1200, 1200, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"bandwidth":"4TB"}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb","imageSlug":"ubuntu-22-04-x64"}'::jsonb, true),
  ('do-vps-basic-2vcpu-4gb-lon1', 'vps'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'lon1',
   'VPS Basic (2 vCPU / 4 GB)', 1200, 1200, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"bandwidth":"4TB"}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb","imageSlug":"ubuntu-22-04-x64"}'::jsonb, true),
  ('do-vps-basic-2vcpu-4gb-sgp1', 'vps'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sgp1',
   'VPS Basic (2 vCPU / 4 GB)', 1200, 1200, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"bandwidth":"4TB"}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb","imageSlug":"ubuntu-22-04-x64"}'::jsonb, true),

  -- Kubernetes Basic 3-node cluster — 5 regions
  ('do-k8s-basic-3node-nyc3', 'kubernetes'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'nyc3',
   'Kubernetes Basic (3 nodes)', 3600, 3600, 'monthly'::public.billing_cycle,
   null, null, null, '{"nodes":3,"nodeSize":"s-2vcpu-4gb"}'::jsonb,
   '{"nodeSize":"s-2vcpu-4gb","nodeCount":3}'::jsonb, true),
  ('do-k8s-basic-3node-sfo3', 'kubernetes'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sfo3',
   'Kubernetes Basic (3 nodes)', 3600, 3600, 'monthly'::public.billing_cycle,
   null, null, null, '{"nodes":3,"nodeSize":"s-2vcpu-4gb"}'::jsonb,
   '{"nodeSize":"s-2vcpu-4gb","nodeCount":3}'::jsonb, true),
  ('do-k8s-basic-3node-fra1', 'kubernetes'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'fra1',
   'Kubernetes Basic (3 nodes)', 3600, 3600, 'monthly'::public.billing_cycle,
   null, null, null, '{"nodes":3,"nodeSize":"s-2vcpu-4gb"}'::jsonb,
   '{"nodeSize":"s-2vcpu-4gb","nodeCount":3}'::jsonb, true),
  ('do-k8s-basic-3node-lon1', 'kubernetes'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'lon1',
   'Kubernetes Basic (3 nodes)', 3600, 3600, 'monthly'::public.billing_cycle,
   null, null, null, '{"nodes":3,"nodeSize":"s-2vcpu-4gb"}'::jsonb,
   '{"nodeSize":"s-2vcpu-4gb","nodeCount":3}'::jsonb, true),
  ('do-k8s-basic-3node-sgp1', 'kubernetes'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sgp1',
   'Kubernetes Basic (3 nodes)', 3600, 3600, 'monthly'::public.billing_cycle,
   null, null, null, '{"nodes":3,"nodeSize":"s-2vcpu-4gb"}'::jsonb,
   '{"nodeSize":"s-2vcpu-4gb","nodeCount":3}'::jsonb, true),

  -- Managed PostgreSQL Basic — 5 regions
  ('do-db-pg-basic-nyc3', 'database'::public.service_type, 'digitalocean', 'db-s-1vcpu-1gb', 'nyc3',
   'Managed PostgreSQL Basic', 1500, 1500, 'monthly'::public.billing_cycle,
   1, 1024, 25, '{"engine":"PostgreSQL","connections":20}'::jsonb,
   '{"engine":"pg","version":"16","size":"db-s-1vcpu-1gb"}'::jsonb, true),
  ('do-db-pg-basic-sfo3', 'database'::public.service_type, 'digitalocean', 'db-s-1vcpu-1gb', 'sfo3',
   'Managed PostgreSQL Basic', 1500, 1500, 'monthly'::public.billing_cycle,
   1, 1024, 25, '{"engine":"PostgreSQL","connections":20}'::jsonb,
   '{"engine":"pg","version":"16","size":"db-s-1vcpu-1gb"}'::jsonb, true),
  ('do-db-pg-basic-fra1', 'database'::public.service_type, 'digitalocean', 'db-s-1vcpu-1gb', 'fra1',
   'Managed PostgreSQL Basic', 1500, 1500, 'monthly'::public.billing_cycle,
   1, 1024, 25, '{"engine":"PostgreSQL","connections":20}'::jsonb,
   '{"engine":"pg","version":"16","size":"db-s-1vcpu-1gb"}'::jsonb, true),
  ('do-db-pg-basic-lon1', 'database'::public.service_type, 'digitalocean', 'db-s-1vcpu-1gb', 'lon1',
   'Managed PostgreSQL Basic', 1500, 1500, 'monthly'::public.billing_cycle,
   1, 1024, 25, '{"engine":"PostgreSQL","connections":20}'::jsonb,
   '{"engine":"pg","version":"16","size":"db-s-1vcpu-1gb"}'::jsonb, true),
  ('do-db-pg-basic-sgp1', 'database'::public.service_type, 'digitalocean', 'db-s-1vcpu-1gb', 'sgp1',
   'Managed PostgreSQL Basic', 1500, 1500, 'monthly'::public.billing_cycle,
   1, 1024, 25, '{"engine":"PostgreSQL","connections":20}'::jsonb,
   '{"engine":"pg","version":"16","size":"db-s-1vcpu-1gb"}'::jsonb, true),

  -- GPU NVIDIA H100 (hourly billing, limited regions)
  ('do-gpu-h100-1x-nyc3', 'gpu'::public.service_type, 'digitalocean', 'gpu-h100x1-80gb', 'nyc3',
   'GPU H100 80 GB (1×)', 250, 250, 'hourly'::public.billing_cycle,
   16, 245760, 300, '{"gpu":"NVIDIA H100","vram":"80GB HBM3"}'::jsonb,
   '{"sizeSlug":"gpu-h100x1-80gb"}'::jsonb, true),
  ('do-gpu-h100-1x-fra1', 'gpu'::public.service_type, 'digitalocean', 'gpu-h100x1-80gb', 'fra1',
   'GPU H100 80 GB (1×)', 250, 250, 'hourly'::public.billing_cycle,
   16, 245760, 300, '{"gpu":"NVIDIA H100","vram":"80GB HBM3"}'::jsonb,
   '{"sizeSlug":"gpu-h100x1-80gb"}'::jsonb, true),

  -- Game Server Basic 2 vCPU / 4 GB — 5 regions
  ('do-game-basic-2vcpu-4gb-nyc3', 'game_server'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'nyc3',
   'Game Server Basic (2 vCPU / 4 GB)', 1400, 1400, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"playerSlots":256}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb"}'::jsonb, true),
  ('do-game-basic-2vcpu-4gb-sfo3', 'game_server'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sfo3',
   'Game Server Basic (2 vCPU / 4 GB)', 1400, 1400, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"playerSlots":256}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb"}'::jsonb, true),
  ('do-game-basic-2vcpu-4gb-fra1', 'game_server'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'fra1',
   'Game Server Basic (2 vCPU / 4 GB)', 1400, 1400, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"playerSlots":256}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb"}'::jsonb, true),
  ('do-game-basic-2vcpu-4gb-lon1', 'game_server'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'lon1',
   'Game Server Basic (2 vCPU / 4 GB)', 1400, 1400, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"playerSlots":256}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb"}'::jsonb, true),
  ('do-game-basic-2vcpu-4gb-sgp1', 'game_server'::public.service_type, 'digitalocean', 's-2vcpu-4gb', 'sgp1',
   'Game Server Basic (2 vCPU / 4 GB)', 1400, 1400, 'monthly'::public.billing_cycle,
   2, 4096, 80, '{"playerSlots":256}'::jsonb,
   '{"sizeSlug":"s-2vcpu-4gb"}'::jsonb, true)
on conflict (plan_code) do update set
  service_type       = excluded.service_type,
  provider           = excluded.provider,
  provider_sku       = excluded.provider_sku,
  region             = excluded.region,
  display_name       = excluded.display_name,
  base_cost_cents    = excluded.base_cost_cents,
  sell_price_cents   = excluded.sell_price_cents,
  billing_cycle      = excluded.billing_cycle,
  vcpu               = excluded.vcpu,
  memory_mb          = excluded.memory_mb,
  storage_gb         = excluded.storage_gb,
  quota              = excluded.quota,
  metadata           = excluded.metadata,
  is_active          = excluded.is_active;
